### ISSUE TITLE
Consider using queue interprop as abstraction for queues

### ISSUE THREAD

**Issue by makasim** [dbojdo/message-bus-amqp#1]
Hello!

Please look at https://github.com/queue-interop/queue-interop project. Using interfaces from it allows us reuse some implementations like enqueue, which supports a lot of transports. You can outsource some code

**Comment by dbojdo** [comment]
I'm closing this due as this lib is not intended to serve any general purpose. Actually is just one of the transport implementations of super-simplified Message Bus implementation, thus it is not meant to be used anywhere else.
